In [397]:
import pandas as pd
import numpy as np
from sklearn import metrics
dataset = pd.read_csv("datasetobservasi.csv")
dataset.head()
# variabel bebas
x = dataset.drop(["Kelas"], axis = 1)
x.head()
#variabel tidak bebas
y = dataset["Kelas"]
y.head()

0    Tidak Manis
1    Tidak Manis
2    Tidak Manis
3    Tidak Manis
4    Tidak Manis
Name: Kelas, dtype: object

In [398]:
# classification 
# please install scikit library 
# pip install -U scikit-learn 

# separate the dataset 
from sklearn.model_selection import train_test_split 

#split data uji
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.3, random_state=1)

#split data validasi
x_train, x_val, y_train, y_val = train_test_split(
    x_train, y_train, test_size=0.43, random_state=1)  


#train_ratio = 0.80
#validation_ratio = 0.10
#test_ratio = 0.10

# train is now 75% of the entire data set
# the _junk suffix means that we drop that variable completely
#x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1 - train_ratio)

# test is now 10% of the initial data set
# validation is now 15% of the initial data set
#x_val, x_test, y_val, y_test = train_test_split(x_test, y_test, test_size=test_ratio/(test_ratio + validation_ratio)) 


x_train.info()
x_val.info()
x_test.info() 
#print(y_train, y_val, y_test)
#import from library 
from sklearn.naive_bayes import GaussianNB 
# Call Gaussian Naive Bayes 
dataset_model = GaussianNB()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 31 entries, 71 to 68
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      31 non-null     float64
 1   X2      31 non-null     float64
 2   X3      31 non-null     float64
dtypes: float64(3)
memory usage: 992.0 bytes
<class 'pandas.core.frame.DataFrame'>
Int64Index: 25 entries, 50 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      25 non-null     float64
 1   X2      25 non-null     float64
 2   X3      25 non-null     float64
dtypes: float64(3)
memory usage: 800.0 bytes
<class 'pandas.core.frame.DataFrame'>
Int64Index: 24 entries, 63 to 56
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   X1      24 non-null     float64
 1   X2      24 non-null     float64
 2   X3      24 non-null     float64
dtypes: float64(3)
memory usage: 768.0 bytes


In [399]:
# Insert the training dataset to Naive Bayes function (validasi)
NB_train = dataset_model.fit(x_train, y_train)

In [400]:
# Next step: Prediction the x_test to the model built and save to the y_pred variable (validasi)
# show the result of prediction
y_pred = NB_train.predict(x_val)
np.array(y_pred)
# show the y_test based on separation dataset
np.array(y_val)

array(['Manis', 'Sangat Manis', 'Tidak Manis', 'Tidak Manis',
       'Kurang Manis', 'Kurang Manis', 'Tidak Manis', 'Manis',
       'Sangat Manis', 'Kurang Manis', 'Kurang Manis', 'Tidak Manis',
       'Tidak Manis', 'Kurang Manis', 'Sangat Manis', 'Sangat Manis',
       'Tidak Manis', 'Tidak Manis', 'Manis', 'Manis', 'Manis',
       'Kurang Manis', 'Kurang Manis', 'Manis', 'Tidak Manis'],
      dtype=object)

In [401]:
# this value will show all probability for each predicted class (validasi)
NB_train.predict_proba(x_test)

array([[2.71957952e-28, 1.75643145e-34, 1.00000000e+00, 1.17559547e-21],
       [4.20363725e-13, 9.99998962e-01, 8.87413552e-07, 1.50164691e-07],
       [2.96304078e-04, 4.64431664e-10, 6.28386140e-01, 3.71317555e-01],
       [1.98354672e-16, 1.19777109e-20, 9.99999986e-01, 1.42127629e-08],
       [3.36559001e-02, 9.20483982e-09, 8.51153655e-01, 1.15190436e-01],
       [7.97526683e-01, 8.93718249e-05, 3.77245380e-03, 1.98611491e-01],
       [1.31176689e-08, 9.99986951e-01, 3.03241422e-06, 1.00031530e-05],
       [6.54405106e-25, 8.06397528e-27, 1.00000000e+00, 1.27893326e-12],
       [3.82513232e-02, 5.42507378e-06, 3.96304725e-03, 9.57780205e-01],
       [5.37455697e-35, 3.13401576e-39, 1.00000000e+00, 1.82855357e-27],
       [5.97713211e-03, 4.04281023e-07, 9.70108872e-03, 9.84321375e-01],
       [8.05773763e-01, 4.38558935e-03, 3.31947662e-03, 1.86521171e-01],
       [7.54313526e-01, 4.65943214e-03, 5.38348431e-04, 2.40488693e-01],
       [3.79584648e-02, 4.02545928e-09, 8.66006730e

In [402]:
# show the confusion matrix based on the prediction result (validasi)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_val,y_pred)

array([[2, 1, 0, 4],
       [0, 6, 0, 0],
       [0, 0, 4, 0],
       [1, 0, 0, 7]], dtype=int64)

In [403]:
print("Accuracy: ",metrics.accuracy_score(y_val, y_pred))

Accuracy:  0.76


In [404]:
#evaluate performance from the confusion matrix (validasi)
from sklearn.metrics import classification_report
print(classification_report(y_val, y_pred))

              precision    recall  f1-score   support

Kurang Manis       0.67      0.29      0.40         7
       Manis       0.86      1.00      0.92         6
Sangat Manis       1.00      1.00      1.00         4
 Tidak Manis       0.64      0.88      0.74         8

    accuracy                           0.76        25
   macro avg       0.79      0.79      0.76        25
weighted avg       0.76      0.76      0.73        25



In [405]:
# Insert the training dataset to Naive Bayes function (uji)
NB_train = dataset_model.fit(x_train, y_train)

In [406]:
# Next step: Prediction the x_test to the model built and save to the y_pred variable (uji)
# show the result of prediction
y_pred = NB_train.predict(x_test)
np.array(y_pred)
# show the y_test based on separation dataset
np.array(y_test)

array(['Sangat Manis', 'Manis', 'Tidak Manis', 'Sangat Manis',
       'Kurang Manis', 'Kurang Manis', 'Manis', 'Sangat Manis',
       'Tidak Manis', 'Sangat Manis', 'Tidak Manis', 'Sangat Manis',
       'Tidak Manis', 'Kurang Manis', 'Manis', 'Kurang Manis',
       'Tidak Manis', 'Tidak Manis', 'Tidak Manis', 'Tidak Manis',
       'Manis', 'Kurang Manis', 'Sangat Manis', 'Manis'], dtype=object)

In [407]:
# this value will show all probability for each predicted class (uji)
NB_train.predict_proba(x_test)

array([[2.71957952e-28, 1.75643145e-34, 1.00000000e+00, 1.17559547e-21],
       [4.20363725e-13, 9.99998962e-01, 8.87413552e-07, 1.50164691e-07],
       [2.96304078e-04, 4.64431664e-10, 6.28386140e-01, 3.71317555e-01],
       [1.98354672e-16, 1.19777109e-20, 9.99999986e-01, 1.42127629e-08],
       [3.36559001e-02, 9.20483982e-09, 8.51153655e-01, 1.15190436e-01],
       [7.97526683e-01, 8.93718249e-05, 3.77245380e-03, 1.98611491e-01],
       [1.31176689e-08, 9.99986951e-01, 3.03241422e-06, 1.00031530e-05],
       [6.54405106e-25, 8.06397528e-27, 1.00000000e+00, 1.27893326e-12],
       [3.82513232e-02, 5.42507378e-06, 3.96304725e-03, 9.57780205e-01],
       [5.37455697e-35, 3.13401576e-39, 1.00000000e+00, 1.82855357e-27],
       [5.97713211e-03, 4.04281023e-07, 9.70108872e-03, 9.84321375e-01],
       [8.05773763e-01, 4.38558935e-03, 3.31947662e-03, 1.86521171e-01],
       [7.54313526e-01, 4.65943214e-03, 5.38348431e-04, 2.40488693e-01],
       [3.79584648e-02, 4.02545928e-09, 8.66006730e

In [408]:
# show the confusion matrix based on the prediction result (uji)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1, 0, 3, 1],
       [1, 4, 0, 0],
       [1, 0, 5, 0],
       [1, 0, 1, 6]], dtype=int64)

In [409]:
print("Accuracy: ",metrics.accuracy_score(y_test, y_pred))

Accuracy:  0.6666666666666666


In [410]:
#evaluate performance from the confusion matrix (uji)
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

Kurang Manis       0.25      0.20      0.22         5
       Manis       1.00      0.80      0.89         5
Sangat Manis       0.56      0.83      0.67         6
 Tidak Manis       0.86      0.75      0.80         8

    accuracy                           0.67        24
   macro avg       0.67      0.65      0.64        24
weighted avg       0.69      0.67      0.66        24

